{"numFailedTestSuites":1,"numFailedTests":3,"numPassedTestSuites":0,"numPassedTests":3,"numPendingTestSuites":0,"numPendingTests":0,"numRuntimeErrorTestSuites":0,"numTodoTests":0,"numTotalTestSuites":1,"numTotalTests":3,"openHandles":[],"snapshot":{"added":0,"didUpdate":false,"failure":false,"filesAdded":0,"filesRemoved":0,"filesRemovedList":[],"filesUnmatched":0,"filesUpdated":0,"matched":0,"total":0,"unchecked":0,"uncheckedKeysByFile":[],"unmatched":0,"updated":0},"startTime":1660825471393,"success":false,"testResults":[{"assertionResults":[{"ancestorTitles":["Stories with failures","ComponentThrowsErrors"],"duration":25,"failureMessages":["page.evaluate: StorybookTestRunnerError: \nAn error occurred in the following story. Access the link for full output:\nhttp://localhost:6006/iframe.html?path=/story/stories-with-failures--component-throws-errors&addonPanel=storybook/interactions/panel\n\nMessage:\n The story was missing when trying to access it.\n\n\n--------------------------------------------------\n\nBrowser logs:\n\n\u001b[1m\u001b[31merror\u001b[39m\u001b[22m: Unable to load story 'stories-with-failures--component-throws-errors':\n\n\u001b[1m\u001b[31merror\u001b[39m\u001b[22m: {}\n    at Object.<anonymous> (<anonymous>:161:13)\n    at http://localhost:6006/node_modules/.vite-storybook/deps/chunk-3LEMKDGI.js?v=7bc24d5e:205:14\n    at Array.forEach (<anonymous>)\n    at Channel2.handleEvent (http://localhost:6006/node_modules/.vite-storybook/deps/chunk-3LEMKDGI.js?v=7bc24d5e:204:19)\n    at handler2 (http://localhost:6006/node_modules/.vite-storybook/deps/chunk-3LEMKDGI.js?v=7bc24d5e:134:16)\n    at Channel2.emit (http://localhost:6006/node_modules/.vite-storybook/deps/chunk-3LEMKDGI.js?v=7bc24d5e:139:9)\n    at PreviewWeb2.renderStoryLoadingException (http://localhost:6006/node_modules/.vite-storybook/deps/chunk-JAZQKNJU.js?v=7bc24d5e:2832:20)\n    at PreviewWeb2._callee8$ (http://localhost:6006/node_modules/.vite-storybook/deps/chunk-JAZQKNJU.js?v=7bc24d5e:2633:22)\n    at tryCatch (http://localhost:6006/node_modules/.vite-storybook/deps/chunk-OLDILCDE.js?v=7bc24d5e:43:44)\n    at Generator.invoke [as _invoke] (http://localhost:6006/node_modules/.vite-storybook/deps/chunk-OLDILCDE.js?v=7bc24d5e:190:26)\n    at testFn (/Users/yannbraga/open-source/test-runner/stories/expected-failures/Page.stories.jsx:35:37)\n    at Object.<anonymous> (/Users/yannbraga/open-source/test-runner/stories/expected-failures/Page.stories.jsx:54:17)\n    at Promise.then.completed (/Users/yannbraga/open-source/test-runner/node_modules/jest-circus/build/utils.js:333:28)\n    at callAsyncCircusFn (/Users/yannbraga/open-source/test-runner/node_modules/jest-circus/build/utils.js:259:10)\n    at _callCircusTest (/Users/yannbraga/open-source/test-runner/node_modules/jest-circus/build/run.js:277:40)\n    at _runTest (/Users/yannbraga/open-source/test-runner/node_modules/jest-circus/build/run.js:209:3)\n    at _runTestsForDescribeBlock (/Users/yannbraga/open-source/test-runner/node_modules/jest-circus/build/run.js:97:9)\n    at _runTestsForDescribeBlock (/Users/yannbraga/open-source/test-runner/node_modules/jest-circus/build/run.js:91:9)\n    at _runTestsForDescribeBlock (/Users/yannbraga/open-source/test-runner/node_modules/jest-circus/build/run.js:91:9)\n    at run (/Users/yannbraga/open-source/test-runner/node_modules/jest-circus/build/run.js:31:3)\n    at runAndTransformResultsToJestFormat (/Users/yannbraga/open-source/test-runner/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:135:21)\n    at jestAdapter (/Users/yannbraga/open-source/test-runner/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:92:19)\n    at runTestInternal (/Users/yannbraga/open-source/test-runner/node_modules/jest-runner/build/runTest.js:411:16)\n    at runTest (/Users/yannbraga/open-source/test-runner/node_modules/jest-runner/build/runTest.js:499:34)"],"fullName":"Stories with failures ComponentThrowsErrors smoke-test","location":null,"status":"failed","title":"smoke-test"},{"ancestorTitles":["Stories with failures","PlayFnThrowsErrors"],"duration":26,"failureMessages":["page.evaluate: StorybookTestRunnerError: \nAn error occurred in the following story. Access the link for full output:\nhttp://localhost:6006/iframe.html?path=/story/stories-with-failures--play-fn-throws-errors&addonPanel=storybook/interactions/panel\n\nMessage:\n The story was missing when trying to access it.\n\n\n--------------------------------------------------\n\nBrowser logs:\n\n\u001b[1m\u001b[31merror\u001b[39m\u001b[22m: Unable to load story 'stories-with-failures--play-fn-throws-errors':\n\n\u001b[1m\u001b[31merror\u001b[39m\u001b[22m: {}\n    at Object.<anonymous> (<anonymous>:161:13)\n    at http://localhost:6006/node_modules/.vite-storybook/deps/chunk-3LEMKDGI.js?v=7bc24d5e:205:14\n    at Array.forEach (<anonymous>)\n    at Channel2.handleEvent (http://localhost:6006/node_modules/.vite-storybook/deps/chunk-3LEMKDGI.js?v=7bc24d5e:204:19)\n    at handler2 (http://localhost:6006/node_modules/.vite-storybook/deps/chunk-3LEMKDGI.js?v=7bc24d5e:134:16)\n    at Channel2.emit (http://localhost:6006/node_modules/.vite-storybook/deps/chunk-3LEMKDGI.js?v=7bc24d5e:139:9)\n    at PreviewWeb2.renderStoryLoadingException (http://localhost:6006/node_modules/.vite-storybook/deps/chunk-JAZQKNJU.js?v=7bc24d5e:2832:20)\n    at PreviewWeb2._callee8$ (http://localhost:6006/node_modules/.vite-storybook/deps/chunk-JAZQKNJU.js?v=7bc24d5e:2633:22)\n    at tryCatch (http://localhost:6006/node_modules/.vite-storybook/deps/chunk-OLDILCDE.js?v=7bc24d5e:43:44)\n    at Generator.invoke [as _invoke] (http://localhost:6006/node_modules/.vite-storybook/deps/chunk-OLDILCDE.js?v=7bc24d5e:190:26)\n    at testFn (/Users/yannbraga/open-source/test-runner/stories/expected-failures/Page.stories.jsx:88:37)\n    at Object.<anonymous> (/Users/yannbraga/open-source/test-runner/stories/expected-failures/Page.stories.jsx:107:17)\n    at Promise.then.completed (/Users/yannbraga/open-source/test-runner/node_modules/jest-circus/build/utils.js:333:28)\n    at callAsyncCircusFn (/Users/yannbraga/open-source/test-runner/node_modules/jest-circus/build/utils.js:259:10)\n    at _callCircusTest (/Users/yannbraga/open-source/test-runner/node_modules/jest-circus/build/run.js:277:40)\n    at _runTest (/Users/yannbraga/open-source/test-runner/node_modules/jest-circus/build/run.js:209:3)\n    at _runTestsForDescribeBlock (/Users/yannbraga/open-source/test-runner/node_modules/jest-circus/build/run.js:97:9)\n    at _runTestsForDescribeBlock (/Users/yannbraga/open-source/test-runner/node_modules/jest-circus/build/run.js:91:9)\n    at _runTestsForDescribeBlock (/Users/yannbraga/open-source/test-runner/node_modules/jest-circus/build/run.js:91:9)\n    at run (/Users/yannbraga/open-source/test-runner/node_modules/jest-circus/build/run.js:31:3)\n    at runAndTransformResultsToJestFormat (/Users/yannbraga/open-source/test-runner/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:135:21)\n    at jestAdapter (/Users/yannbraga/open-source/test-runner/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:92:19)\n    at runTestInternal (/Users/yannbraga/open-source/test-runner/node_modules/jest-runner/build/runTest.js:411:16)\n    at runTest (/Users/yannbraga/open-source/test-runner/node_modules/jest-runner/build/runTest.js:499:34)"],"fullName":"Stories with failures PlayFnThrowsErrors play-test","location":null,"status":"failed","title":"play-test"},{"ancestorTitles":["Stories with failures","PlayFnAssertionFails"],"duration":43,"failureMessages":["page.evaluate: StorybookTestRunnerError: \nAn error occurred in the following story. Access the link for full output:\nhttp://localhost:6006/iframe.html?path=/story/stories-with-failures--play-fn-assertion-fails&addonPanel=storybook/interactions/panel\n\nMessage:\n The story was missing when trying to access it.\n\n\n--------------------------------------------------\n\nBrowser logs:\n\n\u001b[1m\u001b[31merror\u001b[39m\u001b[22m: Unable to load story 'stories-with-failures--play-fn-assertion-fails':\n\n\u001b[1m\u001b[31merror\u001b[39m\u001b[22m: {}\n    at Object.<anonymous> (<anonymous>:161:13)\n    at http://localhost:6006/node_modules/.vite-storybook/deps/chunk-3LEMKDGI.js?v=7bc24d5e:205:14\n    at Array.forEach (<anonymous>)\n    at Channel2.handleEvent (http://localhost:6006/node_modules/.vite-storybook/deps/chunk-3LEMKDGI.js?v=7bc24d5e:204:19)\n    at handler2 (http://localhost:6006/node_modules/.vite-storybook/deps/chunk-3LEMKDGI.js?v=7bc24d5e:134:16)\n    at Channel2.emit (http://localhost:6006/node_modules/.vite-storybook/deps/chunk-3LEMKDGI.js?v=7bc24d5e:139:9)\n    at PreviewWeb2.renderStoryLoadingException (http://localhost:6006/node_modules/.vite-storybook/deps/chunk-JAZQKNJU.js?v=7bc24d5e:2832:20)\n    at PreviewWeb2._callee8$ (http://localhost:6006/node_modules/.vite-storybook/deps/chunk-JAZQKNJU.js?v=7bc24d5e:2633:22)\n    at tryCatch (http://localhost:6006/node_modules/.vite-storybook/deps/chunk-OLDILCDE.js?v=7bc24d5e:43:44)\n    at Generator.invoke [as _invoke] (http://localhost:6006/node_modules/.vite-storybook/deps/chunk-OLDILCDE.js?v=7bc24d5e:190:26)\n    at testFn (/Users/yannbraga/open-source/test-runner/stories/expected-failures/Page.stories.jsx:141:37)\n    at Object.<anonymous> (/Users/yannbraga/open-source/test-runner/stories/expected-failures/Page.stories.jsx:160:17)\n    at Promise.then.completed (/Users/yannbraga/open-source/test-runner/node_modules/jest-circus/build/utils.js:333:28)\n    at callAsyncCircusFn (/Users/yannbraga/open-source/test-runner/node_modules/jest-circus/build/utils.js:259:10)\n    at _callCircusTest (/Users/yannbraga/open-source/test-runner/node_modules/jest-circus/build/run.js:277:40)\n    at _runTest (/Users/yannbraga/open-source/test-runner/node_modules/jest-circus/build/run.js:209:3)\n    at _runTestsForDescribeBlock (/Users/yannbraga/open-source/test-runner/node_modules/jest-circus/build/run.js:97:9)\n    at _runTestsForDescribeBlock (/Users/yannbraga/open-source/test-runner/node_modules/jest-circus/build/run.js:91:9)\n    at _runTestsForDescribeBlock (/Users/yannbraga/open-source/test-runner/node_modules/jest-circus/build/run.js:91:9)\n    at run (/Users/yannbraga/open-source/test-runner/node_modules/jest-circus/build/run.js:31:3)\n    at runAndTransformResultsToJestFormat (/Users/yannbraga/open-source/test-runner/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:135:21)\n    at jestAdapter (/Users/yannbraga/open-source/test-runner/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:92:19)\n    at runTestInternal (/Users/yannbraga/open-source/test-runner/node_modules/jest-runner/build/runTest.js:411:16)\n    at runTest (/Users/yannbraga/open-source/test-runner/node_modules/jest-runner/build/runTest.js:499:34)"],"fullName":"Stories with failures PlayFnAssertionFails play-test","location":null,"status":"failed","title":"play-test"}],"endTime":1660825475405,"message":"\u001b[1m\u001b[31m  \u001b[1m● \u001b[22m\u001b[1mStories with failures › ComponentThrowsErrors › smoke-test\u001b[39m\u001b[22m\n\n    page.evaluate: StorybookTestRunnerError: \n    An error occurred in the following story. Access the link for full output:\n    http://localhost:6006/iframe.html?path=/story/stories-with-failures--component-throws-errors&addonPanel=storybook/interactions/panel\n\n    Message:\n     The story was missing when trying to access it.\n\n\n    --------------------------------------------------\n\n    Browser logs:\n\n    \u001b[1m\u001b[31merror\u001b[39m\u001b[22m: Unable to load story 'stories-with-failures--component-throws-errors':\n\n    \u001b[1m\u001b[31merror\u001b[39m\u001b[22m: {}\n\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat Object.<anonymous> (\u001b[22m\u001b[2m<anonymous>\u001b[2m:161:13)\u001b[22m\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat \u001b[22m\u001b[2mhttp:/localhost:6006/node_modules/.vite-storybook/deps/chunk-3LEMKDGI.js?v=7bc24d5e\u001b[2m:205:14\u001b[22m\u001b[2m\u001b[22m\n\u001b[2m          at Array.forEach (<anonymous>)\u001b[22m\n\u001b[2m      \u001b[2mat Channel2.handleEvent (\u001b[22m\u001b[2mhttp:/localhost:6006/node_modules/.vite-storybook/deps/chunk-3LEMKDGI.js?v=7bc24d5e\u001b[2m:204:19)\u001b[22m\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat handler2 (\u001b[22m\u001b[2mhttp:/localhost:6006/node_modules/.vite-storybook/deps/chunk-3LEMKDGI.js?v=7bc24d5e\u001b[2m:134:16)\u001b[22m\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat Channel2.emit (\u001b[22m\u001b[2mhttp:/localhost:6006/node_modules/.vite-storybook/deps/chunk-3LEMKDGI.js?v=7bc24d5e\u001b[2m:139:9)\u001b[22m\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat PreviewWeb2.renderStoryLoadingException (\u001b[22m\u001b[2mhttp:/localhost:6006/node_modules/.vite-storybook/deps/chunk-JAZQKNJU.js?v=7bc24d5e\u001b[2m:2832:20)\u001b[22m\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat PreviewWeb2._callee8$ (\u001b[22m\u001b[2mhttp:/localhost:6006/node_modules/.vite-storybook/deps/chunk-JAZQKNJU.js?v=7bc24d5e\u001b[2m:2633:22)\u001b[22m\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat tryCatch (\u001b[22m\u001b[2mhttp:/localhost:6006/node_modules/.vite-storybook/deps/chunk-OLDILCDE.js?v=7bc24d5e\u001b[2m:43:44)\u001b[22m\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat Generator.invoke [as _invoke] (\u001b[22m\u001b[2mhttp:/localhost:6006/node_modules/.vite-storybook/deps/chunk-OLDILCDE.js?v=7bc24d5e\u001b[2m:190:26)\u001b[22m\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat testFn (\u001b[22m\u001b[2m\u001b[0m\u001b[36mstories/expected-failures/Page.stories.jsx\u001b[39m\u001b[0m\u001b[2m:35:37)\u001b[22m\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat Object.<anonymous> (\u001b[22m\u001b[2m\u001b[0m\u001b[36mstories/expected-failures/Page.stories.jsx\u001b[39m\u001b[0m\u001b[2m:54:17)\u001b[22m\u001b[2m\u001b[22m\n\n\u001b[1m\u001b[31m  \u001b[1m● \u001b[22m\u001b[1mStories with failures › PlayFnThrowsErrors › play-test\u001b[39m\u001b[22m\n\n    page.evaluate: StorybookTestRunnerError: \n    An error occurred in the following story. Access the link for full output:\n    http://localhost:6006/iframe.html?path=/story/stories-with-failures--play-fn-throws-errors&addonPanel=storybook/interactions/panel\n\n    Message:\n     The story was missing when trying to access it.\n\n\n    --------------------------------------------------\n\n    Browser logs:\n\n    \u001b[1m\u001b[31merror\u001b[39m\u001b[22m: Unable to load story 'stories-with-failures--play-fn-throws-errors':\n\n    \u001b[1m\u001b[31merror\u001b[39m\u001b[22m: {}\n\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat Object.<anonymous> (\u001b[22m\u001b[2m<anonymous>\u001b[2m:161:13)\u001b[22m\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat \u001b[22m\u001b[2mhttp:/localhost:6006/node_modules/.vite-storybook/deps/chunk-3LEMKDGI.js?v=7bc24d5e\u001b[2m:205:14\u001b[22m\u001b[2m\u001b[22m\n\u001b[2m          at Array.forEach (<anonymous>)\u001b[22m\n\u001b[2m      \u001b[2mat Channel2.handleEvent (\u001b[22m\u001b[2mhttp:/localhost:6006/node_modules/.vite-storybook/deps/chunk-3LEMKDGI.js?v=7bc24d5e\u001b[2m:204:19)\u001b[22m\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat handler2 (\u001b[22m\u001b[2mhttp:/localhost:6006/node_modules/.vite-storybook/deps/chunk-3LEMKDGI.js?v=7bc24d5e\u001b[2m:134:16)\u001b[22m\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat Channel2.emit (\u001b[22m\u001b[2mhttp:/localhost:6006/node_modules/.vite-storybook/deps/chunk-3LEMKDGI.js?v=7bc24d5e\u001b[2m:139:9)\u001b[22m\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat PreviewWeb2.renderStoryLoadingException (\u001b[22m\u001b[2mhttp:/localhost:6006/node_modules/.vite-storybook/deps/chunk-JAZQKNJU.js?v=7bc24d5e\u001b[2m:2832:20)\u001b[22m\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat PreviewWeb2._callee8$ (\u001b[22m\u001b[2mhttp:/localhost:6006/node_modules/.vite-storybook/deps/chunk-JAZQKNJU.js?v=7bc24d5e\u001b[2m:2633:22)\u001b[22m\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat tryCatch (\u001b[22m\u001b[2mhttp:/localhost:6006/node_modules/.vite-storybook/deps/chunk-OLDILCDE.js?v=7bc24d5e\u001b[2m:43:44)\u001b[22m\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat Generator.invoke [as _invoke] (\u001b[22m\u001b[2mhttp:/localhost:6006/node_modules/.vite-storybook/deps/chunk-OLDILCDE.js?v=7bc24d5e\u001b[2m:190:26)\u001b[22m\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat testFn (\u001b[22m\u001b[2m\u001b[0m\u001b[36mstories/expected-failures/Page.stories.jsx\u001b[39m\u001b[0m\u001b[2m:88:37)\u001b[22m\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat Object.<anonymous> (\u001b[22m\u001b[2m\u001b[0m\u001b[36mstories/expected-failures/Page.stories.jsx\u001b[39m\u001b[0m\u001b[2m:107:17)\u001b[22m\u001b[2m\u001b[22m\n\n\u001b[1m\u001b[31m  \u001b[1m● \u001b[22m\u001b[1mStories with failures › PlayFnAssertionFails › play-test\u001b[39m\u001b[22m\n\n    page.evaluate: StorybookTestRunnerError: \n    An error occurred in the following story. Access the link for full output:\n    http://localhost:6006/iframe.html?path=/story/stories-with-failures--play-fn-assertion-fails&addonPanel=storybook/interactions/panel\n\n    Message:\n     The story was missing when trying to access it.\n\n\n    --------------------------------------------------\n\n    Browser logs:\n\n    \u001b[1m\u001b[31merror\u001b[39m\u001b[22m: Unable to load story 'stories-with-failures--play-fn-assertion-fails':\n\n    \u001b[1m\u001b[31merror\u001b[39m\u001b[22m: {}\n\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat Object.<anonymous> (\u001b[22m\u001b[2m<anonymous>\u001b[2m:161:13)\u001b[22m\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat \u001b[22m\u001b[2mhttp:/localhost:6006/node_modules/.vite-storybook/deps/chunk-3LEMKDGI.js?v=7bc24d5e\u001b[2m:205:14\u001b[22m\u001b[2m\u001b[22m\n\u001b[2m          at Array.forEach (<anonymous>)\u001b[22m\n\u001b[2m      \u001b[2mat Channel2.handleEvent (\u001b[22m\u001b[2mhttp:/localhost:6006/node_modules/.vite-storybook/deps/chunk-3LEMKDGI.js?v=7bc24d5e\u001b[2m:204:19)\u001b[22m\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat handler2 (\u001b[22m\u001b[2mhttp:/localhost:6006/node_modules/.vite-storybook/deps/chunk-3LEMKDGI.js?v=7bc24d5e\u001b[2m:134:16)\u001b[22m\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat Channel2.emit (\u001b[22m\u001b[2mhttp:/localhost:6006/node_modules/.vite-storybook/deps/chunk-3LEMKDGI.js?v=7bc24d5e\u001b[2m:139:9)\u001b[22m\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat PreviewWeb2.renderStoryLoadingException (\u001b[22m\u001b[2mhttp:/localhost:6006/node_modules/.vite-storybook/deps/chunk-JAZQKNJU.js?v=7bc24d5e\u001b[2m:2832:20)\u001b[22m\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat PreviewWeb2._callee8$ (\u001b[22m\u001b[2mhttp:/localhost:6006/node_modules/.vite-storybook/deps/chunk-JAZQKNJU.js?v=7bc24d5e\u001b[2m:2633:22)\u001b[22m\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat tryCatch (\u001b[22m\u001b[2mhttp:/localhost:6006/node_modules/.vite-storybook/deps/chunk-OLDILCDE.js?v=7bc24d5e\u001b[2m:43:44)\u001b[22m\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat Generator.invoke [as _invoke] (\u001b[22m\u001b[2mhttp:/localhost:6006/node_modules/.vite-storybook/deps/chunk-OLDILCDE.js?v=7bc24d5e\u001b[2m:190:26)\u001b[22m\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat testFn (\u001b[22m\u001b[2m\u001b[0m\u001b[36mstories/expected-failures/Page.stories.jsx\u001b[39m\u001b[0m\u001b[2m:141:37)\u001b[22m\u001b[2m\u001b[22m\n\u001b[2m      \u001b[2mat Object.<anonymous> (\u001b[22m\u001b[2m\u001b[0m\u001b[36mstories/expected-failures/Page.stories.jsx\u001b[39m\u001b[0m\u001b[2m:160:17)\u001b[22m\u001b[2m\u001b[22m\n","name":"/Users/yannbraga/open-source/test-runner/stories/expected-failures/Page.stories.jsx","startTime":1660825472199,"status":"failed","summary":""}]}